# We from the Oslo project decided to pin repos based on the
# commit hash instead of the version tag to prevend arbitrary
# code from running in developer's machines.  To update to a
# newer version, run `pre-commit autoupdate` and then replace
# the newer versions with their commit hash.

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ebc15addedad713c86ef18ae9632c88e187dd0af  # v3.1.0
    hooks:
      - id: trailing-whitespace
      # Replaces or checks mixed line ending
      - id: mixed-line-ending
        args: ['--fix', 'lf']
        exclude: '.*\.(svg)$'
      # Forbid files which have a UTF-8 byte-order marker
      - id: check-byte-order-marker
      # Checks that non-binary executables have a proper shebang
      - id: check-executables-have-shebangs
      # Check for files that contain merge conflict strings.
      - id: check-merge-conflict
      # Check for debugger imports and py37+ breakpoint()
      # calls in python source
      - id: debug-statements
      - id: check-yaml
        files: .*\.(yaml|yml)$
  - repo: https://gitlab.com/pycqa/flake8
    rev: aa792d2930b8f6dada3f6305e8a3704d2d191005 # 3.7.8
    hooks:
      - id: flake8
        additional_dependencies:
          - hacking>=3.0.1,<3.1.0
